### ISSUE TITLE
Install seemingly fails quietly

### ISSUE THREAD

**Issue by brennanwilkes** [zerotier/github-action#29]
Pretty simple,

I'm running:
```
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_ACCESS_TOKEN }}
```

and seeing the following output before experiencing a crash (with zero additional information)

```
Run zerotier/github-action@v1
Run zerotier/github-action/util/post@main
⏁  Installing ZeroTier
```

**Comment by brennanwilkes** [comment]
Note: fails with both `zerotier/github-action@v1` and `zerotier/github-action@v1.0.3`

**Comment by brennanwilkes** [comment]
Note: Isn't present with `zerotier/github-action@v1.0.2` so it's like an issue with the new path variable

**Comment by brennanwilkes** [comment]
Also seems to be frustratingly inconsistent. I was initially able to get past the issue by downgrading to `v1.0.2`, but subsequent pipeline runs failed all the same

**Comment by laduke** [comment]
Thanks for reporting. I'm not super familiar with the internals of this action. Will try to take a look soon.

**Comment by brennanwilkes** [comment]
Thanks @laduke. Apologies that I don't have more information, the crash seemingly doesn't produce logs.

![Screenshot from 2024-09-10 12-18-29](https://github.com/user-attachments/assets/a31a8ef4-ba2d-48e9-9c1d-dd36ff8c26a2)


```
2024-09-10T18:53:16.6216480Z ⏁  Installing ZeroTier
2024-09-10T18:53:16.9055188Z Post job cleanup.
2024-09-10T18:53:16.9113718Z Post job cleanup.
2024-09-10T18:53:16.9817446Z ⏁  Removing Runner from ZeroTier network
2024-09-10T18:53:17.7591245Z Success! Status code: 200
2024-09-10T18:53:17.7721890Z Post job cleanup.
```

**Comment by axelvazq** [comment]
@brennanwilkes I been using zerotier for my github actions consistent for months, zerotier install requires curl so make sure your runner has it.
```yml
   deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.3
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ```
